#!/usr/bin/env python3
"""Check static docs links, fragments, source references and retired commands."""
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit, unquote
import re

ROOT = Path(__file__).resolve().parent.parent
class Page(HTMLParser):
    def __init__(self, path):
        super().__init__()
        self.ids, self.links = set(), []
        self.feed(path.read_text(encoding="utf-8"))
    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if "id" in attrs:
            if attrs["id"] in self.ids:
                raise ValueError("duplicate id: " + attrs["id"])
            self.ids.add(attrs["id"])
        for attr in ("href", "src"):
            if attrs.get(attr):
                self.links.append(attrs[attr])

pages = {p.resolve(): Page(p) for p in (ROOT / "docs").rglob("*.html")}
errors = []
for path, page in pages.items():
    text = path.read_text(encoding="utf-8")
    for stale in (r"\bpnpm\b", r"core/src/", r"harness/src/", r"legacy-interop", r"\.mjs\b", r"archived v0\.2"):
        if re.search(stale, text):
            errors.append(f"{path.relative_to(ROOT)}: stale reference {stale}")
    for link in page.links:
        u = urlsplit(link)
        prefix = "https://github.com/botiverse/k-carrier/"
        if link.startswith(prefix + "blob/main/") or link.startswith(prefix + "tree/main/"):
            target = ROOT / unquote(u.path.split("/main/", 1)[1])
        elif u.scheme or u.netloc:
            continue
        else:
            target = (path.parent / unquote(u.path)).resolve() if u.path else path
        if not target.exists():
            errors.append(f"{path.relative_to(ROOT)}: missing {link}")
        elif not u.scheme and u.fragment and target in pages and unquote(u.fragment) not in pages[target].ids:
            errors.append(f"{path.relative_to(ROOT)}: missing fragment {link}")
# Navigation is generated by this static-site asset.
for link in re.findall(r"\['([^']+\.html)',", (ROOT / 'docs/assets/site.js').read_text(encoding="utf-8")):
    if not (ROOT / 'docs' / link).is_file():
        errors.append('navigation: missing ' + link)
if errors:
    raise SystemExit('\n'.join(errors))
print(f"Checked {len(pages)} HTML pages, local fragments, source links and navigation")
